name = "shopify-orders"
main = "dist/worker.js"
compatibility_date = "2025-04-28"

[dev]
port = 8787
local_protocol = "http"

[vars]
GATSBY_SHOPIFY_STORE_URL = { type = "secret_text" }
SHOPIFY_SHOP_PASSWORD = { type = "secret_text" }